### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by jrmuizel** [comment]
Unfortunately, I feel like this makes the code somewhat harder to read. For now, I'd prefer more targeted fixes to places where the formatting is egregiously bad.

**Comment by Atul9** [comment]
Regarding - `targeted fixes to places where the formatting is egregiously bad` - Can you please point out those places?

**Comment by Atul9** [comment]
@jrmuizel Regarding - targeted fixes to places where the formatting is egregiously bad - Can you please point out those places?

**Comment by jrmuizel** [comment]
I'm not sure what they are. You'd need to look at the cargo fmt results and see which changes make things obviously better to read.

**Pull request closed without merging**
